import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    app_title: 'CycloneShield',
    tagline: 'Predict. Protect. Respond.',
    hero_subtitle: 'Turn cyclone forecasts into local, actionable decisions before landfall.',
    simulation_notice: 'Simulation Mode: All predictions are calculated from synthetic sample data and are not official warnings.',
    model_methodology_link: 'Model Methodology →',
    start_guided_demo: 'Start Guided Demo (3 Min)',
    ai_briefing_btn: 'AI Situation Brief',
    view_fullscreen_map: 'View Fullscreen Impact Map →',
    eoc_title: 'Emergency Operations Center (EOC) • Sundar Coast Sector',
    situation_at_glance: 'Situation at a Glance',
    nav_overview: 'Overview',
    nav_map: 'Live Impact Map',
    nav_evacuation: 'Evacuation Plan',
    nav_infrastructure: 'Infrastructure Risks',
    nav_simulator: 'Scenario Simulator',
    nav_briefing: 'AI Situation Brief',
    nav_alerts: 'Alert Drafts',
    nav_methodology: 'Data & Method',
    role_officer: 'District Emergency Officer',
    role_station: 'EOC Sundar Coast',
    time_to_landfall: 'T–24h to Landfall',
    updated_just_now: 'Updated just now',
    what_needs_attention: 'What Needs Attention Now',
    click_to_drill_down: 'Click any metric to drill down',
    evac_priority_title: 'Evacuation Priority',
    critical_assets_title: 'Critical Assets',
    roads_risk_title: 'Road Corridors',
    shelter_gap_title: 'Shelter Capacity Gap',
    priority_locations_title: 'Top Priority Locations Requiring Immediate Action',
    why_at_risk_btn: 'Why At Risk?',
    view_on_map_btn: 'View on Map',
    cyclone_trajectory_timeline: 'CYCLONE TRAJECTORY TIMELINE',
    landfall_in_24h: 'Landfall in 24 Hours',
    sustained_wind: 'Sustained Wind',
    rainfall_24h: '24h Rainfall',
    peak_surge: 'Peak Surge',
    confidence: 'Confidence',
    gale_winds: 'Gale force winds',
    heavy_rain: 'Heavy precipitation',
    inundation_risk: 'Inundation risk',
    high_confidence: 'High confidence',
    tactical_phase_desc: 'T–24h Tactical Phase: Gale winds and surge begin within 18 hours. Complete all P0 village evacuations before nightfall.',
    p0_action: 'Immediate Evacuation Required',
    navigation_header: 'Navigation',
    active_scenario: 'Cyclone Varuna • Sundar Coast District',
    confidence_chip: '78% confidence',
  },
  hi: {
    app_title: 'साइक्लोनशील्ड',
    tagline: 'पूर्वानुमान। सुरक्षा। प्रतिक्रिया।',
    hero_subtitle: 'चक्रवात के पूर्वानुमान को लैंडफॉल से पहले स्थानीय, त्वरित निर्णयों में बदलें।',
    simulation_notice: 'सिमुलेशन मोड: सभी भविष्यवाणियां सिंथेटिक नमूना डेटा से तैयार की गई हैं और यह आधिकारिक चेतावनी नहीं है।',
    model_methodology_link: 'मॉडल कार्यप्रणाली →',
    start_guided_demo: 'निर्देशित डेमो शुरू करें (3 मिनट)',
    ai_briefing_btn: 'एआई स्थिति ब्रीफिंग',
    view_fullscreen_map: 'पूर्णस्क्रीन प्रभाव मानचित्र देखें →',
    eoc_title: 'आपातकालीन संचालन केंद्र (EOC) • सुंदर तट क्षेत्र',
    situation_at_glance: 'वर्तमान स्थिति का अवलोकन',
    nav_overview: 'अवलोकन',
    nav_map: 'लाइव प्रभाव मानचित्र',
    nav_evacuation: 'निकासी योजना',
    nav_infrastructure: 'बुनियादी ढांचा जोखिम',
    nav_simulator: 'परिदृश्य सिम्युलेटर',
    nav_briefing: 'एआई स्थिति रिपोर्ट',
    nav_alerts: 'चेतावनी मसौदे',
    nav_methodology: 'डेटा और पद्धति',
    role_officer: 'जिला आपातकालीन अधिकारी',
    role_station: 'ईओसी सुंदर तट',
    time_to_landfall: 'लैंडफॉल में 24 घंटे शेष',
    updated_just_now: 'अभी अपडेट किया गया',
    what_needs_attention: 'तत्काल ध्यान देने योग्य मुख्य बिंदु',
    click_to_drill_down: 'विस्तृत जानकारी के लिए किसी भी मीट्रिक पर क्लिक करें',
    evac_priority_title: 'निकासी प्राथमिकता',
    critical_assets_title: 'महत्वपूर्ण संपत्तियां',
    roads_risk_title: 'सड़क गलियारे',
    shelter_gap_title: 'आश्रय क्षमता का अंतर',
    priority_locations_title: 'तत्काल कार्रवाई की आवश्यकता वाले शीर्ष प्राथमिकता वाले क्षेत्र',
    why_at_risk_btn: 'जोखिम क्यों है?',
    view_on_map_btn: 'मानचित्र पर देखें',
    cyclone_trajectory_timeline: 'चक्रवात प्रक्षेपवक्र समयरेखा',
    landfall_in_24h: '24 घंटे में लैंडफॉल',
    sustained_wind: 'हवा की गति',
    rainfall_24h: '24 घंटे की वर्षा',
    peak_surge: 'अधिकतम तूफानी लहर',
    confidence: 'मॉडल विश्वास',
    gale_winds: 'तीव्र आंधी की हवाएं',
    heavy_rain: 'भारी वर्षा की संभावना',
    inundation_risk: 'जलभराव और बाढ़ का जोखिम',
    high_confidence: 'उच्च विश्वसनीयता',
    tactical_phase_desc: 'T–24h रणनीति चरण: 18 घंटों के भीतर तूफानी हवाएं शुरू होंगी। रात होने से पहले सभी P0 गांवों की निकासी पूरी करें।',
    p0_action: 'तत्काल निकासी आवश्यक',
    navigation_header: 'नेविगेशन',
    active_scenario: 'चक्रवात वरुणा • सुंदर तट जिला',
    confidence_chip: '78% विश्वसनीयता',
  },
  bn: {
    app_title: 'সাইক্লোনশিল্ড',
    tagline: 'পূর্বাভাস। সুরক্ষা। প্রতিক্রিয়া।',
    hero_subtitle: 'ঘূর্ণিঝড়ের পূর্বাভাসকে ল্যান্ডফলের আগেই কার্যকর স্থানীয় সিদ্ধান্তে রূপান্তর করুন।',
    simulation_notice: 'সিমুলেশন মোড: সমস্ত পূর্বাভাস নমুনা ডেটা থেকে তৈরি এবং এটি সরকারি সতর্কবার্তা নয়।',
    model_methodology_link: 'মডেল পদ্ধতি →',
    start_guided_demo: 'নির্দেশিত ডেমো শুরু করুন (৩ মিনিট)',
    ai_briefing_btn: 'এআই পরিস্থিতি ব্রিফিং',
    view_fullscreen_map: 'ফুলস্ক্রিন প্রভাব মানচিত্র দেখুন →',
    eoc_title: 'জরুরি অপারেশন সেন্টার (EOC) • সুন্দর উপকূল অঞ্চল',
    situation_at_glance: 'এক নজরে সামগ্রিক পরিস্থিতি',
    nav_overview: 'সংক্ষিপ্ত বিবরণ',
    nav_map: 'লাইভ প্রভাব মানচিত্র',
    nav_evacuation: 'স্থানান্তর পরিকল্পনা',
    nav_infrastructure: 'পরিকাঠামো ঝুঁকি',
    nav_simulator: 'পরিস্থিতি সিমুলেটর',
    nav_briefing: 'এআই ব্রিফিং',
    nav_alerts: 'সতর্কবার্তা ড্রাফট',
    nav_methodology: 'উপাত্ত ও পদ্ধতি',
    role_officer: 'জেলা জরুরি কর্মকর্তা',
    role_station: 'ইওসি সুন্দর উপকূল',
    time_to_landfall: 'ল্যান্ডফলের ২৪ ঘণ্টা বাকি',
    updated_just_now: 'এখনই আপডেট হয়েছে',
    what_needs_attention: 'এখনই যে বিষয়গুলিতে নজর দেওয়া জরুরি',
    click_to_drill_down: 'বিস্তারিত দেখতে যেকোনো মেট্রিক্সে ক্লিক করুন',
    evac_priority_title: 'স্থানান্তর অগ্রাধিকার',
    critical_assets_title: 'জরুরি পরিকাঠামো',
    roads_risk_title: 'ঝুঁকিপূর্ণ সড়ক',
    shelter_gap_title: 'আশ্রয়কেন্দ্রের ঘাটতি',
    priority_locations_title: 'তাৎক্ষণিক পদক্ষেপের প্রয়োজন এমন শীর্ষ এলাকা',
    why_at_risk_btn: 'কেন ঝুঁকিপূর্ণ?',
    view_on_map_btn: 'মানচিত্রে দেখুন',
    cyclone_trajectory_timeline: 'ঘূর্ণিঝড় গতিপথ সময়রেখা',
    landfall_in_24h: '২৪ ঘণ্টায় ল্যান্ডফল',
    sustained_wind: 'বাতাসের গতিবেগ',
    rainfall_24h: '২৪ ঘণ্টার বৃষ্টিপাত',
    peak_surge: 'সর্বোচ্চ জলোচ্ছ্বাস',
    confidence: 'মডেল নির্ভরযোগ্যতা',
    gale_winds: 'প্রবল ঝড়ো বাতাস',
    heavy_rain: 'ভারী বর্ষণ',
    inundation_risk: 'প্লাবনের ঝুঁকি',
    high_confidence: 'উচ্চ নির্ভরযোগ্যতা',
    tactical_phase_desc: 'T–24h কৌশলগত পর্যায়: ১৮ ঘণ্টার মধ্যে ঝড়ো হাওয়া ও জলোচ্ছ্বাস শুরু হবে। সন্ধ্যার আগেই সমস্ত P0 গ্রামের স্থানান্তর সম্পন্ন করুন।',
    p0_action: 'জরুরি স্থানান্তর প্রয়োজন',
    navigation_header: 'মেনু নেভিগেশন',
    active_scenario: 'ঘূর্ণিঝড় বরুণ • সুন্দর উপকূল জেলা',
    confidence_chip: '৭৮% নির্ভরযোগ্যতা',
  },
  or: {
    app_title: 'ସାଇକ୍ଲୋନସିଲ୍ଡ',
    tagline: 'ପୂର୍ବାନୁମାନ। ସୁରକ୍ଷା। ପ୍ରତିକ୍ରିୟା।',
    hero_subtitle: 'ବାତ୍ୟା ପୂର୍ବାନୁମାନକୁ ସ୍ଥଳଭାଗ ଛୁଇଁବା ପୂର୍ବରୁ ସ୍ଥାନୀୟ କାର୍ଯ୍ୟାନୁଷ୍ଠାନ ଯୋଗ୍ୟ ନିଷ୍ପତ୍ତିରେ ପରିଣତ କରନ୍ତୁ।',
    simulation_notice: 'ସିମ୍ୟୁଲେସନ ମୋଡ୍: ସମସ୍ତ ପୂର୍ବାନୁମାନ ନମୁନା ତଥ୍ୟ ଉପରେ ଆଧାରିତ ଏବଂ ଏହା ସରକାରୀ ଚେତାବନୀ ନୁହେଁ।',
    model_methodology_link: 'ମଡେଲ ପଦ୍ଧତି →',
    start_guided_demo: 'ମାର୍ଗଦର୍ଶିତ ଡେମୋ ଆରମ୍ଭ କରନ୍ତୁ (୩ ମିନିଟ)',
    ai_briefing_btn: 'ଏଆଇ ପରିସ୍ଥିତି ବ୍ରିଫିଂ',
    view_fullscreen_map: 'ସମ୍ପୂର୍ଣ୍ଣ ପ୍ରଭାବ ମାନଚିତ୍ର ଦେଖନ୍ତୁ →',
    eoc_title: 'ଜରୁରୀକାଳୀନ ପରିଚାଳନା କେନ୍ଦ୍ର (EOC) • ସୁନ୍ଦର ଉପକୂଳ କ୍ଷେତ୍ର',
    situation_at_glance: 'ଏକ ନଜରରେ ପରିସ୍ଥିତି',
    nav_overview: 'ସମୀକ୍ଷା',
    nav_map: 'ପ୍ରତ୍ୟକ୍ଷ ପ୍ରଭାବ ମାନଚିତ୍ର',
    nav_evacuation: 'ସ୍ଥାନାନ୍ତର ଯୋଜନା',
    nav_infrastructure: 'ଭିତ୍ତିଭୂମି ବିପଦ',
    nav_simulator: 'ଦୃଶ୍ୟପଟ ସିମ୍ୟୁଲେଟର',
    nav_briefing: 'ଏଆଇ ବ୍ରିଫିଂ',
    nav_alerts: 'ସତର୍କତା ଚିଠା',
    nav_methodology: 'ତଥ୍ୟ ଓ ପଦ୍ଧତି',
    role_officer: 'ଜିଲ୍ଲା ଜରୁରୀକାଳୀନ ଅଧିକାରୀ',
    role_station: 'ଇଓସି ସୁନ୍ଦର ଉପକୂଳ',
    time_to_landfall: 'ସ୍ଥଳଭାଗ ଛୁଇଁବାକୁ ୨୪ ଘଣ୍ଟା ବାକି',
    updated_just_now: 'ଏବେ ଅପଡେଟ ହୋଇଛି',
    what_needs_attention: 'ଏବେ ତୁରନ୍ତ ଧ୍ୟାନ ଦେବା ଆବଶ୍ୟକ',
    click_to_drill_down: 'ଅଧିକ ବିବରଣୀ ପାଇଁ କ୍ଲିକ୍ କରନ୍ତୁ',
    evac_priority_title: 'ସ୍ଥାନାନ୍ତର ପ୍ରାଥମିକତା',
    critical_assets_title: 'ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ସମ୍ପତ୍ତି',
    roads_risk_title: 'ରାସ୍ତା କୋରିଡର',
    shelter_gap_title: 'ଆଶ୍ରୟସ୍ଥଳୀ କ୍ଷମତା ଅଭାବ',
    priority_locations_title: 'ତୁରନ୍ତ ପଦକ୍ଷେପ ଆବଶ୍ୟକ କରୁଥିବା ଶୀର୍ଷ ପ୍ରାଥମିକତା ସ୍ଥାନ',
    why_at_risk_btn: 'କାହିଁକି ବିପଦରେ?',
    view_on_map_btn: 'ମାନଚିତ୍ରରେ ଦେଖନ୍ତୁ',
    cyclone_trajectory_timeline: 'ବାତ୍ୟା ଗତିପଥ ସମୟସୀମା',
    landfall_in_24h: '୨୪ ଘଣ୍ଟାରେ ସ୍ଥଳଭାଗ ଛୁଇଁବ',
    sustained_wind: 'ପବନର ବେଗ',
    rainfall_24h: '୨୪ ଘଣ୍ଟାର ବର୍ଷା',
    peak_surge: 'ଜୁଆରର ଉଚ୍ଚତା',
    confidence: 'ମଡେଲ ବିଶ୍ୱସନୀୟତା',
    gale_winds: 'ପ୍ରବଳ ବେଗରେ ପବନ',
    heavy_rain: 'ପ୍ରବଳ ବର୍ଷା',
    inundation_risk: 'ଜଳମଗ୍ନ ହେବାର ଆଶଙ୍କା',
    high_confidence: 'ଉଚ୍ଚ ବିଶ୍ୱସନୀୟତା',
    tactical_phase_desc: 'T–24h ରଣନୀତି ପର୍ଯ୍ୟାୟ: ୧୮ ଘଣ୍ଟା ମଧ୍ୟରେ ପ୍ରବଳ ପବନ ଓ ଜୁଆର ଆରମ୍ଭ ହେବ। ସନ୍ଧ୍ୟା ପୂର୍ବରୁ ସମସ୍ତ P0 ଗ୍ରାମର ସ୍ଥାନାନ୍ତର ଶେଷ କରନ୍ତୁ।',
    p0_action: 'ତୁରନ୍ତ ସ୍ଥାନାନ୍ତର ଆବଶ୍ୟକ',
    navigation_header: 'ନେଭିଗେସନ୍',
    active_scenario: 'ବାତ୍ୟା ବରୁଣ • ସୁନ୍ଦର ଉପକୂଳ ଜିଲ୍ଲା',
    confidence_chip: '୭୮% ବିଶ୍ୱସନୀୟତା',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
